services:
  - type: web
    name: amazon-clone
    env: node
    buildCommand: npm install && npm run heroku-postbuild
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE
        sync: false
      - key: KEY
        sync: false
